
const data = [
    {vehicalId:1,
    section:"Car",
    type:"Hatchback",
    model:"Kia Rio",
    available:"Yes"},
    
    {vehicalId:2,
     section:"Car",
    type:"SUV",
    model:"Honda Pilot",
    available:"Yes"},
    
    {vehicalId:3,
    section:"Car",
    type:"Sedan",
    model:"Kia Optima",
    available:"Yes"},
    
    {vehicalId:4,
    section:"Bike",
    type:"Sports",
    model:"Yamaha YZF-R1",
available:"Yes"},
{vehicalId:5,
    section:"Bike",
    type:"Sports",
    model:"KTM RC8 R",
available:"Yes"},
{vehicalId:6,
    section:"Car",
    type:"Sedan",
    model:"Honda Accord",
    available:"Yes"},
    {vehicalId:7,
        section:"Car",
        type:"SUV",
        model:"Toyota RAV4",
        available:"Yes"},
        {vehicalId:8,
            section:"Car",
            type:"Hatchback",
            model:"Hyundai Veloster",
            available:"Yes"},]
// console.log(data)
exports.data = data;